apiVersion: v1
data:
  database.sql: "\ncreate table texasholder_user (\n\tuid int(11) auto_increment,\n\taccount
    varchar(50) default '',\n\tpassword varchar(20) default '',\n\troommoney int(11)
    default 0,\n\tallmoney int(11) default 100000,\n\texprience int default 0,\n\tgold
    int default 0,\n\tmobile varchar(20),\n\tlevel int default 0,\n\tsex varchar(10)
    default 'male',\n\taddress varchar(50) default '',\n\tregtime varchar(30) default
    '',\n\tbirthday varchar(30) default '',\n\tlogintime varchar(20) default '',\n\tprimary
    key(uid),\n\tUNIQUE KEY uidx_account (account)\n)ENGINE=InnoDB DEFAULT CHARSET=utf8;\n\nINSERT
    INTO texasholder_user (\n    account, password, roommoney, allmoney, exprience, gold,
    mobile, level, sex, address, regtime, birthday, logintime\n) VALUES\n('user1',
    'pass123', 0, 100000, 0, 0, '13800000001', 1, 'male', 'Address 1', '2025-01-01
    10:00:00', '1990-01-01', '2025-01-01 10:00:00'),\n('user2', 'pass123', 0, 100000,
    0, 0, '13800000002', 2, 'female', 'Address 2', '2025-01-02 11:00:00', '1991-02-02',
    '2025-01-02 11:00:00'),\n('user3', 'pass123', 0, 100000, 0, 0, '13800000003',
    3, 'male', 'Address 3', '2025-01-03 12:00:00', '1992-03-03', '2025-01-03 12:00:00'),\n('user4',
    'pass123', 0, 100000, 0, 0, '13800000004', 4, 'female', 'Address 4', '2025-01-04
    13:00:00', '1993-04-04', '2025-01-04 13:00:00'),\n('user5', 'pass123', 0, 100000,
    0, 0, '13800000005', 5, 'male', 'Address 5', '2025-01-05 14:00:00', '1994-05-05',
    '2025-01-05 14:00:00'),\n('user6', 'pass123', 0, 100000, 0, 0, '13800000006',
    6, 'female', 'Address 6', '2025-01-06 15:00:00', '1995-06-06', '2025-01-06 15:00:00'),\n('user7',
    'pass123', 0, 100000, 0, 0, '13800000007', 7, 'male', 'Address 7', '2025-01-07
    16:00:00', '1996-07-07', '2025-01-07 16:00:00'),\n('user8', 'pass123', 0, 100000,
    0, 0, '13800000008', 8, 'female', 'Address 8', '2025-01-08 17:00:00', '1997-08-08',
    '2025-01-08 17:00:00'),\n('user9', 'pass123', 0, 100000, 0, 0, '13800000009',
    9, 'male', 'Address 9', '2025-01-09 18:00:00', '1998-09-09', '2025-01-09 18:00:00'),\n('user10',
    'pass123', 0, 100000, 0, 0, '13800000010', 10, 'female', 'Address 10', '2025-01-10
    19:00:00', '1999-10-10', '2025-01-10 19:00:00'),\n('user11', 'pass123', 0, 100000,
    0, 0, '13800000011', 11, 'male', 'Address 11', '2025-01-11 20:00:00', '2000-11-11',
    '2025-01-11 20:00:00'),\n('user12', 'pass123', 0, 100000, 0, 0, '13800000012',
    12, 'female', 'Address 12', '2025-01-12 21:00:00', '2001-12-12', '2025-01-12 21:00:00'),\n('user13',
    'pass123', 0, 100000, 0, 0, '13800000013', 13, 'male', 'Address 13', '2025-01-13
    22:00:00', '2002-01-13', '2025-01-13 22:00:00'),\n('user14', 'pass123', 0, 100000,
    0, 0, '13800000014', 14, 'female', 'Address 14', '2025-01-14 23:00:00', '2003-02-14',
    '2025-01-14 23:00:00'),\n('user15', 'pass123', 0, 100000, 0, 0, '13800000015',
    15, 'male', 'Address 15', '2025-01-15 00:00:00', '2004-03-15', '2025-01-15 00:00:00'),\n('user16',
    'pass123', 0, 100000, 0, 0, '13800000016', 16, 'female', 'Address 16', '2025-01-16
    01:00:00', '2005-04-16', '2025-01-16 01:00:00'),\n('user17', 'pass123', 0, 100000,
    0, 0, '13800000017', 17, 'male', 'Address 17', '2025-01-17 02:00:00', '2006-05-17',
    '2025-01-17 02:00:00'),\n('user18', 'pass123', 0, 100000, 0, 0, '13800000018',
    18, 'female', 'Address 18', '2025-01-18 03:00:00', '2007-06-18', '2025-01-18 03:00:00'),\n('user19',
    'pass123', 0, 100000, 0, 0, '13800000019', 19, 'male', 'Address 19', '2025-01-19
    04:00:00', '2008-07-19', '2025-01-19 04:00:00'),\n('user20', 'pass123', 0, 100000,
    0, 0, '13800000020', 20, 'female', 'Address 20', '2025-01-20 05:00:00', '2009-08-20',
    '2025-01-20 05:00:00'),\n('user21', 'pass123', 0, 100000, 0, 0, '13800000021',
    21, 'male', 'Address 21', '2025-01-21 06:00:00', '2010-09-21', '2025-01-21 06:00:00'),\n('user22',
    'pass123', 0, 100000, 0, 0, '13800000022', 22, 'female', 'Address 22', '2025-01-22
    07:00:00', '2011-10-22', '2025-01-22 07:00:00'),\n('user23', 'pass123', 0, 100000,
    0, 0, '13800000023', 23, 'male', 'Address 23', '2025-01-23 08:00:00', '2012-11-23',
    '2025-01-23 08:00:00'),\n('user24', 'pass123', 0, 100000, 0, 0, '13800000024',
    24, 'female', 'Address 24', '2025-01-24 09:00:00', '2013-12-24', '2025-01-24 09:00:00'),\n('user25',
    'pass123', 0, 100000, 0, 0, '13800000025', 25, 'male', 'Address 25', '2025-01-25
    10:00:00', '2014-01-25', '2025-01-25 10:00:00'),\n('user26', 'pass123', 0, 100000,
    0, 0, '13800000026', 26, 'female', 'Address 26', '2025-01-26 11:00:00', '2015-02-26',
    '2025-01-26 11:00:00'),\n('user27', 'pass123', 0, 100000, 0, 0, '13800000027',
    27, 'male', 'Address 27', '2025-01-27 12:00:00', '2016-03-27', '2025-01-27 12:00:00'),\n('user28',
    'pass123', 0, 100000, 0, 0, '13800000028', 28, 'female', 'Address 28', '2025-01-28
    13:00:00', '2017-04-28', '2025-01-28 13:00:00'),\n('user29', 'pass123', 0, 100000,
    0, 0, '13800000029', 29, 'male', 'Address 29', '2025-01-29 14:00:00', '2018-05-29',
    '2025-01-29 14:00:00'),\n('user30', 'pass123', 0, 100000, 0, 0, '13800000030',
    30, 'female', 'Address 30', '2025-01-30 15:00:00', '2019-06-30', '2025-01-30 15:00:00'),\n('user31',
    'pass123', 0, 100000, 0, 0, '13800000031', 31, 'male', 'Address 31', '2025-02-01
    16:00:00', '2020-07-01', '2025-02-01 16:00:00'),\n('user32', 'pass123', 0, 100000,
    0, 0, '13800000032', 32, 'female', 'Address 32', '2025-02-02 17:00:00', '2021-08-02',
    '2025-02-02 17:00:00'),\n('user33', 'pass123', 0, 100000, 0, 0, '13800000033',
    33, 'male', 'Address 33', '2025-02-03 18:00:00', '2022-09-03', '2025-02-03 18:00:00'),\n('user34',
    'pass123', 0, 100000, 0, 0, '13800000034', 34, 'female', 'Address 34', '2025-02-04
    19:00:00', '2023-10-04', '2025-02-04 19:00:00'),\n('user35', 'pass123', 0, 100000,
    0, 0, '13800000035', 35, 'male', 'Address 35', '2025-02-05 20:00:00', '2024-11-05',
    '2025-02-05 20:00:00'),\n('user36', 'pass123', 0, 100000, 0, 0, '13800000036',
    36, 'female', 'Address 36', '2025-02-06 21:00:00', '2025-12-06', '2025-02-06 21:00:00'),\n('user37',
    'pass123', 0, 100000, 0, 0, '13800000037', 37, 'male', 'Address 37', '2025-02-07
    22:00:00', '1989-01-07', '2025-02-07 22:00:00'),\n('user38', 'pass123', 0, 100000,
    0, 0, '13800000038', 38, 'female', 'Address 38', '2025-02-08 23:00:00', '1988-02-08',
    '2025-02-08 23:00:00'),\n('user39', 'pass123', 0, 100000, 0, 0, '13800000039',
    39, 'male', 'Address 39', '2025-02-09 00:00:00', '1987-03-09', '2025-02-09 00:00:00'),\n('user40',
    'pass123', 0, 100000, 0, 0, '13800000040', 40, 'female', 'Address 40', '2025-02-10
    01:00:00', '1986-04-10', '2025-02-10 01:00:00'),\n('user41', 'pass123', 0, 100000,
    0, 0, '13800000041', 41, 'male', 'Address 41', '2025-02-11 02:00:00', '1985-05-11',
    '2025-02-11 02:00:00'),\n('user42', 'pass123', 0, 100000, 0, 0, '13800000042',
    42, 'female', 'Address 42', '2025-02-12 03:00:00', '1984-06-12', '2025-02-12 03:00:00'),\n('user43',
    'pass123', 0, 100000, 0, 0, '13800000043', 43, 'male', 'Address 43', '2025-02-13
    04:00:00', '1983-07-13', '2025-02-13 04:00:00'),\n('user44', 'pass123', 0, 100000,
    0, 0, '13800000044', 44, 'female', 'Address 44', '2025-02-14 05:00:00', '1982-08-14',
    '2025-02-14 05:00:00'),\n('user45', 'pass123', 0, 100000, 0, 0, '13800000045',
    45, 'male', 'Address 45', '2025-02-15 06:00:00', '1981-09-15', '2025-02-15 06:00:00'),\n('user46',
    'pass123', 0, 100000, 0, 0, '13800000046', 46, 'female', 'Address 46', '2025-02-16
    07:00:00', '1980-10-16', '2025-02-16 07:00:00'),\n('user47', 'pass123', 0, 100000,
    0, 0, '13800000047', 47, 'male', 'Address 47', '2025-02-17 08:00:00', '1979-11-17',
    '2025-02-17 08:00:00'),\n('user48', 'pass123', 0, 100000, 0, 0, '13800000048',
    48, 'female', 'Address 48', '2025-02-18 09:00:00', '1978-12-18', '2025-02-18 09:00:00'),\n('user49',
    'pass123', 0, 100000, 0, 0, '13800000049', 49, 'male', 'Address 49', '2025-02-19
    10:00:00', '1977-01-19', '2025-02-19 10:00:00'),\n('user50', 'pass123', 0, 100000,
    0, 0, '13800000050', 50, 'female', 'Address 50', '2025-02-20 11:00:00', '1976-02-20',
    '2025-02-20 11:00:00');\n\n\ncreate table texasholder_room (\n\tid int(11) auto_increment,\n\tshowname
    varchar(50) default '',\n\tname varchar(50) default '',\n\tbbet int(11) default
    0,\n\tsbet int(11) default 0,\n\tmaxbuy int(11) default 0,\n\tminbuy int(11) default
    0,\n\troomtype varchar(10) default '',\n\tprimary key(id)\n)ENGINE=InnoDB DEFAULT
    CHARSET=utf8;\n\n// generate some rooms please run below sqls\ninsert into texasholder_room
    (showname, name, bbet, sbet, maxbuy, minbuy, roomtype) values ('初级场', 'beginner',
    20, 10, 2000, 200, 'public');\ninsert into texasholder_room (showname, name, bbet,
    sbet, maxbuy, minbuy, roomtype) values ('中级场', 'intermediate', 200, 100, 20000,
    2000, 'public');\ninsert into texasholder_room (showname, name, bbet, sbet, maxbuy,
    minbuy, roomtype) values ('高级场', 'advanced', 2000, 1000, 200000, 20000, 'public');\ninsert
    into texasholder_room (showname, name, bbet, sbet, maxbuy, minbuy, roomtype) values
    ('土豪场', 'tycoon', 20000, 10000, 2000000, 200000, 'public');"
kind: ConfigMap
metadata:
  name: mysql-init-config
